####################################################################################################
# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
####################################################################################################

deepstream:
  nodes:
  - type: filesrc
    name: filesrc
    properties:
      location: /opt/nvidia/deepstream/deepstream/samples/streams/sample_720p.h264
  - type: h264parse
    name: h264parse
  - type: nvv4l2decoder
    name: nvv4l2decoder
  - type: nvstreammux
    name: nvstreammux
    properties:
      batch-size: 1
      width: 1280
      height: 720
  - type: nvinfer
    name: infer
    properties:
      config-file-path: /opt/nvidia/deepstream/deepstream/sources/apps/sample_apps/deepstream-test1/dstest1_pgie_config.yml
## Enabling raw tensor output from inference
#      output-tensor-meta: true
## Inference using nvinferserver: replace the above infer definition with below
#  - type: nvinferserver
#    name: infer
#    properties:
#      config-file-path: /opt/nvidia/deepstream/deepstream/sources/apps/sample_apps/deepstream-test1/dstest1_pgie_nvinferserver_config.txt
  - type: nvvideoconvert
    name: nvvideoconvert
  - type: nvdsosd
    name: nvdsosd
  - type: nveglglessink
    name: sink
    properties:
      sync: false
  - type: sample_video_probe.sample_video_probe
    name: samplevideoprobe
    properties:
      font-size: 15
  edges:
    filesrc: h264parse
    h264parse: nvv4l2decoder
    nvv4l2decoder: nvstreammux
    nvstreammux: infer
    infer: nvvideoconvert
    nvvideoconvert.src:
    - nvdsosd
    - samplevideoprobe
    nvdsosd: sink
