################################################################################
# SPDX-FileCopyrightText: Copyright (c) 2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
################################################################################

source:
  location: ../../../../samples/streams/sample_720p.h264

streammux:
  batch-size: 1
  batched-push-timeout: 40000
  width: 1920
  height: 1080


tracker:
  tracker-width: 960
  tracker-height: 544
  gpu-id: 0
  ll-lib-file: /opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so
  # ll-config-file required to set different tracker types
  # ll-config-file: ../../../../samples/configs/deepstream-app/config_tracker_IOU.yml
  # ll-config-file: ../../../../samples/configs/deepstream-app/config_tracker_NvSORT.yml
  ll-config-file: ../../../../samples/configs/deepstream-app/config_tracker_NvDCF_perf.yml
  # ll-config-file: ../../../../samples/configs/deepstream-app/config_tracker_NvDCF_accuracy.yml
  # ll-config-file: ../../../../samples/configs/deepstream-app/config_tracker_NvDeepSORT.yml

# Inference using nvinfer:
primary-gie:
  plugin-type: 0
  config-file-path: dstest2_pgie_config.yml

secondary-gie1:
  plugin-type: 0
  config-file-path: dstest2_sgie1_config.yml

secondary-gie2:
  plugin-type: 0
  config-file-path: dstest2_sgie2_config.yml


## Inference using nvinferserver:
#primary-gie:
#  plugin-type: 1
#  config-file-path: dstest2_pgie_nvinferserver_config.txt

#secondary-gie1:
#  plugin-type: 1
#  config-file-path: dstest2_sgie1_nvinferserver_config.txt

#secondary-gie2:
#  plugin-type: 1
#  config-file-path: dstest2_sgie2_nvinferserver_config.txt

