%YAML 1.2
################################################################################
# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
################################################################################

# - pts(us): filepath

---
source-list:
  - 0: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00000.bin
  - 100: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00001.bin
  - 200: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00002.bin
  - 300: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00003.bin
  - 400: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00004.bin
  - 500: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00005.bin
  - 600: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00006.bin
  - 700: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00007.bin
  - 800: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00008.bin
  - 900: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00009.bin
  - 1000: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00010.bin
  - 1100: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00011.bin
  - 1200: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00012.bin
  - 1300: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00013.bin
  - 1400: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00014.bin
  - 1500: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00015.bin
  - 1600: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00016.bin
  - 1700: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00017.bin
  - 1800: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00018.bin
  - 1900: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00019.bin
  - 2000: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00020.bin
  - 2100: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00021.bin
  - 2200: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00022.bin
  - 2300: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00023.bin
  - 2400: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00024.bin
  - 2500: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00025.bin
  - 2600: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00026.bin
  - 2700: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00027.bin
  - 2800: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00028.bin
  - 2900: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00029.bin
  - 3000: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00030.bin
  - 3100: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00031.bin
  - 3200: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00032.bin
  - 3300: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00033.bin
  - 3400: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00034.bin
  - 3500: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00035.bin
  - 3600: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00036.bin
  - 3700: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00037.bin
  - 3800: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00038.bin
  - 3900: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00039.bin
  - 4000: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00040.bin
  - 4100: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00041.bin
  - 4200: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00042.bin
  - 4300: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00043.bin
  - 4400: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00044.bin
  - 4500: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00045.bin
  - 4600: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00046.bin
  - 4700: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00047.bin
  - 4800: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00048.bin
  - 4900: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00049.bin
  - 5000: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00050.bin
  - 5100: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00051.bin
  - 5200: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00052.bin
  - 5300: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00053.bin
  - 5400: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00054.bin
  - 5500: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00055.bin
  - 5600: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00056.bin
  - 5700: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00057.bin
  - 5800: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00058.bin
  - 5900: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00059.bin
  - 6000: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00060.bin
  - 6100: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00061.bin
  - 6200: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00062.bin
  - 6300: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00063.bin
  - 6400: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00064.bin
  - 6500: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00065.bin
  - 6600: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00066.bin
  - 6700: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00067.bin
  - 6800: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00068.bin
  - 6900: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00069.bin
  - 7000: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00070.bin
  - 7100: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00071.bin
  - 7200: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00072.bin
  - 7300: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00073.bin
  - 7400: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00074.bin
  - 7500: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00075.bin
  - 7600: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00076.bin
  - 7700: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00077.bin
  - 7800: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00078.bin
  - 7900: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00079.bin
  - 8000: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00080.bin
  - 8100: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00081.bin
  - 8200: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00082.bin
  - 8300: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00083.bin
  - 8400: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00084.bin
  - 8500: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00085.bin
  - 8600: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00086.bin
  - 8700: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00087.bin
  - 8800: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00088.bin
  - 8900: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00089.bin
  - 9000: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00090.bin
  - 9100: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00091.bin
  - 9200: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00092.bin
  - 9300: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00093.bin
  - 9400: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00094.bin
  - 9500: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00095.bin
  - 9600: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00096.bin
  - 9700: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00097.bin
  - 9800: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00098.bin
  - 9900: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00099.bin
  - 10000: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00100.bin
  - 10100: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00101.bin
  - 10200: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00102.bin
  - 10300: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00103.bin
  - 10400: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00104.bin
  - 10500: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00105.bin
  - 10600: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00106.bin
  - 10700: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00107.bin
  - 10800: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00108.bin
  - 10900: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00109.bin
  - 11000: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00110.bin
  - 11100: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00111.bin
  - 11200: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00112.bin
  - 11300: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00113.bin
  - 11400: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00114.bin
  - 11500: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00115.bin
  - 11600: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00116.bin
  - 11700: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00117.bin
  - 11800: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00118.bin
  - 11900: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00119.bin
  - 12000: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00120.bin
  - 12100: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00121.bin
  - 12200: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00122.bin
  - 12300: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00123.bin
  - 12400: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00124.bin
  - 12500: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00125.bin
  - 12600: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00126.bin
  - 12700: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00127.bin
  - 12800: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00128.bin
  - 12900: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00129.bin
  - 13000: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00130.bin
  - 13100: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00131.bin
  - 13200: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00132.bin
  - 13300: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00133.bin
  - 13400: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00134.bin
  - 13500: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00135.bin
  - 13600: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00136.bin
  - 13700: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00137.bin
  - 13800: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00138.bin
  - 13900: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00139.bin
  - 14000: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00140.bin
  - 14100: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00141.bin
  - 14200: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00142.bin
  - 14300: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00143.bin
  - 14400: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00144.bin
  - 14500: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00145.bin
  - 14600: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00146.bin
  - 14700: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00147.bin
  - 14800: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00148.bin
  - 14900: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00149.bin
  - 15000: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00150.bin
  - 15100: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00151.bin
  - 15200: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00152.bin
  - 15300: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00153.bin
  - 15400: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00154.bin
  - 15500: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00155.bin
  - 15600: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00156.bin
  - 15700: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00157.bin
  - 15800: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00158.bin
  - 15900: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00159.bin
  - 16000: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00160.bin
  - 16100: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00161.bin
  - 16200: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00162.bin
  - 16300: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00163.bin
  - 16400: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00164.bin
  - 16500: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00165.bin
  - 16600: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00166.bin
  - 16700: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00167.bin
  - 16800: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00168.bin
  - 16900: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00169.bin
  - 17000: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00170.bin
  - 17100: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00171.bin
  - 17200: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00172.bin
  - 17300: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00173.bin
  - 17400: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00174.bin
  - 17500: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00175.bin
  - 17600: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00176.bin
  - 17700: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00177.bin
  - 17800: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00178.bin
  - 17900: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00179.bin
  - 18000: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00180.bin
  - 18100: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00181.bin
  - 18200: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00182.bin
  - 18300: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00183.bin
  - 18400: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00184.bin
  - 18500: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00185.bin
  - 18600: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00186.bin
  - 18700: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00187.bin
  - 18800: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00188.bin
  - 18900: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00189.bin
  - 19000: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00190.bin
  - 19100: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00191.bin
  - 19200: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00192.bin
  - 19300: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00193.bin
  - 19400: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00194.bin
  - 19500: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00195.bin
  - 19600: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00196.bin
  - 19700: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00197.bin
  - 19800: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00198.bin
  - 19900: ../example-data/v2x-seq.4scenes.10Hz.200frame/3/lidar/lidar_00199.bin
